/*  =========================================================================
    joex - generated layer of public API

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of CZMQ, the high-level C binding for 0MQ:       
    http://czmq.zeromq.org.                                            
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef JOEX_LIBRARY_H_INCLUDED
#define JOEX_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>

//  JOEX version macros for compile-time API detection
#define JOEX_VERSION_MAJOR 0
#define JOEX_VERSION_MINOR 1
#define JOEX_VERSION_PATCH 0

#define JOEX_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define JOEX_VERSION \
    JOEX_MAKE_VERSION(JOEX_VERSION_MAJOR, JOEX_VERSION_MINOR, JOEX_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined JOEX_STATIC
#       define JOEX_EXPORT
#   elif defined JOEX_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define JOEX_EXPORT __declspec(dllexport)
#       else
#           define JOEX_EXPORT
#       endif
#   elif defined JOEX_EXPORTS
#       define JOEX_EXPORT __declspec(dllexport)
#   else
#       define JOEX_EXPORT __declspec(dllimport)
#   endif
#   define JOEX_PRIVATE
#else
#   define JOEX_EXPORT
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define JOEX_PRIVATE __attribute__ ((visibility ("hidden")))
#   else
#       define JOEX_PRIVATE
#   endif
#endif

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
typedef struct _joex_server_t joex_server_t;
#define JOEX_SERVER_T_DEFINED
typedef struct _joex_proto_t joex_proto_t;
#define JOEX_PROTO_T_DEFINED


//  Public classes, each with its own header file
#include "joex_server.h"
#include "joex_proto.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
